// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (tenant_id, slug, name, description, icon, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, slug, name, description, icon, position, is_visible, created_at, updated_at
`

type CreateCategoryParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	Position    int32          `json:"position"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, slug, name, description, icon, position, is_visible, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, tenant_id, slug, name, description, icon, position, is_visible, created_at, updated_at FROM categories WHERE tenant_id = $1 AND slug = $2
`

type GetCategoryBySlugParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, arg.TenantID, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideCategory = `-- name: HideCategory :exec
UPDATE categories SET is_visible = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) HideCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, hideCategory, id)
	return err
}

const listCategoriesByTenant = `-- name: ListCategoriesByTenant :many
SELECT id, tenant_id, slug, name, description, icon, position, is_visible, created_at, updated_at FROM categories
WHERE tenant_id = $1 AND is_visible = true
ORDER BY position ASC
`

func (q *Queries) ListCategoriesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Position,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, description = $3, icon = $4, position = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, slug, name, description, icon, position, is_visible, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	Position    int32          `json:"position"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Position,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
