// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveCourse = `-- name: ArchiveCourse :exec
UPDATE courses SET status = 'archived', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveCourse, id)
	return err
}

const countAllCoursesByTenant = `-- name: CountAllCoursesByTenant :one
SELECT COUNT(*) as count FROM courses WHERE tenant_id = $1
`

func (q *Queries) CountAllCoursesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllCoursesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCoursesByTenant = `-- name: CountCoursesByTenant :one
SELECT COUNT(*) as count FROM courses WHERE tenant_id = $1 AND status = 'published'
`

func (q *Queries) CountCoursesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCoursesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one

INSERT INTO courses (tenant_id, author_id, title, slug, description, thumbnail_url, status)
VALUES ($1, $2, $3, $4, $5, $6, 'draft')
RETURNING id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at
`

type CreateCourseParams struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
}

// ============================================================================
// COURSES
// ============================================================================
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.TenantID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ThumbnailUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at FROM courses WHERE tenant_id = $1 AND slug = $2
`

type GetCourseBySlugParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) GetCourseBySlug(ctx context.Context, arg GetCourseBySlugParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseBySlug, arg.TenantID, arg.Slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseWithDetails = `-- name: GetCourseWithDetails :one
SELECT
    c.id, c.tenant_id, c.author_id, c.title, c.slug, c.description, c.thumbnail_url, c.status, c.published_at, c.module_count, c.lesson_count, c.created_at, c.updated_at,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM courses c
JOIN users u ON c.author_id = u.id
WHERE c.id = $1
`

type GetCourseWithDetailsRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Status       string         `json:"status"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	ModuleCount  int32          `json:"module_count"`
	LessonCount  int32          `json:"lesson_count"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AuthorName   string         `json:"author_name"`
	AuthorAvatar sql.NullString `json:"author_avatar"`
}

func (q *Queries) GetCourseWithDetails(ctx context.Context, id uuid.UUID) (GetCourseWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseWithDetails, id)
	var i GetCourseWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const listAllCoursesByTenant = `-- name: ListAllCoursesByTenant :many
SELECT
    c.id, c.tenant_id, c.author_id, c.title, c.slug, c.description, c.thumbnail_url, c.status, c.published_at, c.module_count, c.lesson_count, c.created_at, c.updated_at,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM courses c
JOIN users u ON c.author_id = u.id
WHERE c.tenant_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllCoursesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListAllCoursesByTenantRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Status       string         `json:"status"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	ModuleCount  int32          `json:"module_count"`
	LessonCount  int32          `json:"lesson_count"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AuthorName   string         `json:"author_name"`
	AuthorAvatar sql.NullString `json:"author_avatar"`
}

func (q *Queries) ListAllCoursesByTenant(ctx context.Context, arg ListAllCoursesByTenantParams) ([]ListAllCoursesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCoursesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCoursesByTenantRow
	for rows.Next() {
		var i ListAllCoursesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ThumbnailUrl,
			&i.Status,
			&i.PublishedAt,
			&i.ModuleCount,
			&i.LessonCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByAuthor = `-- name: ListCoursesByAuthor :many
SELECT id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at FROM courses
WHERE tenant_id = $1 AND author_id = $2
ORDER BY created_at DESC
`

type ListCoursesByAuthorParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) ListCoursesByAuthor(ctx context.Context, arg ListCoursesByAuthorParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCoursesByAuthor, arg.TenantID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ThumbnailUrl,
			&i.Status,
			&i.PublishedAt,
			&i.ModuleCount,
			&i.LessonCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByTenant = `-- name: ListCoursesByTenant :many
SELECT
    c.id, c.tenant_id, c.author_id, c.title, c.slug, c.description, c.thumbnail_url, c.status, c.published_at, c.module_count, c.lesson_count, c.created_at, c.updated_at,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM courses c
JOIN users u ON c.author_id = u.id
WHERE c.tenant_id = $1 AND c.status = 'published'
ORDER BY c.published_at DESC
LIMIT $2 OFFSET $3
`

type ListCoursesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListCoursesByTenantRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Status       string         `json:"status"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	ModuleCount  int32          `json:"module_count"`
	LessonCount  int32          `json:"lesson_count"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AuthorName   string         `json:"author_name"`
	AuthorAvatar sql.NullString `json:"author_avatar"`
}

func (q *Queries) ListCoursesByTenant(ctx context.Context, arg ListCoursesByTenantParams) ([]ListCoursesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoursesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesByTenantRow
	for rows.Next() {
		var i ListCoursesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ThumbnailUrl,
			&i.Status,
			&i.PublishedAt,
			&i.ModuleCount,
			&i.LessonCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishCourse = `-- name: PublishCourse :one
UPDATE courses
SET status = 'published', published_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at
`

func (q *Queries) PublishCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRowContext(ctx, publishCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unpublishCourse = `-- name: UnpublishCourse :one
UPDATE courses
SET status = 'draft', updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at
`

func (q *Queries) UnpublishCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRowContext(ctx, unpublishCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $2, description = $3, thumbnail_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at
`

type UpdateCourseParams struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseSlug = `-- name: UpdateCourseSlug :one
UPDATE courses
SET slug = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, author_id, title, slug, description, thumbnail_url, status, published_at, module_count, lesson_count, created_at, updated_at
`

type UpdateCourseSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateCourseSlug(ctx context.Context, arg UpdateCourseSlugParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, updateCourseSlug, arg.ID, arg.Slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ThumbnailUrl,
		&i.Status,
		&i.PublishedAt,
		&i.ModuleCount,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
