// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countEnrollmentsByCourse = `-- name: CountEnrollmentsByCourse :one
SELECT COUNT(*) as count FROM course_enrollments WHERE course_id = $1
`

func (q *Queries) CountEnrollmentsByCourse(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnrollmentsByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnrollmentsByUser = `-- name: CountEnrollmentsByUser :one
SELECT COUNT(*) as count FROM course_enrollments
WHERE user_id = $1 AND tenant_id = $2 AND status = 'active'
`

type CountEnrollmentsByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CountEnrollmentsByUser(ctx context.Context, arg CountEnrollmentsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnrollmentsByUser, arg.UserID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollment = `-- name: CreateEnrollment :one

INSERT INTO course_enrollments (tenant_id, user_id, course_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, course_id, status, progress_percentage, completed_lessons_count, total_lessons_count, last_lesson_id, last_accessed_at, enrolled_at, completed_at, created_at, updated_at
`

type CreateEnrollmentParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

// ============================================================================
// ENROLLMENTS
// ============================================================================
func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (CourseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, createEnrollment, arg.TenantID, arg.UserID, arg.CourseID)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CompletedLessonsCount,
		&i.TotalLessonsCount,
		&i.LastLessonID,
		&i.LastAccessedAt,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM course_enrollments WHERE id = $1
`

func (q *Queries) DeleteEnrollment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEnrollment, id)
	return err
}

const dropEnrollment = `-- name: DropEnrollment :exec
UPDATE course_enrollments
SET status = 'dropped', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DropEnrollment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, dropEnrollment, id)
	return err
}

const getCompletedCourses = `-- name: GetCompletedCourses :many
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    c.title as course_title,
    c.slug as course_slug,
    c.thumbnail_url as course_thumbnail,
    u.name as author_name
FROM course_enrollments e
JOIN courses c ON e.course_id = c.id
JOIN users u ON c.author_id = u.id
WHERE e.user_id = $1 AND e.tenant_id = $2 AND e.status = 'completed'
ORDER BY e.completed_at DESC
LIMIT $3 OFFSET $4
`

type GetCompletedCoursesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetCompletedCoursesRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	CourseThumbnail       sql.NullString `json:"course_thumbnail"`
	AuthorName            string         `json:"author_name"`
}

func (q *Queries) GetCompletedCourses(ctx context.Context, arg GetCompletedCoursesParams) ([]GetCompletedCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedCourses,
		arg.UserID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletedCoursesRow
	for rows.Next() {
		var i GetCompletedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CourseID,
			&i.Status,
			&i.ProgressPercentage,
			&i.CompletedLessonsCount,
			&i.TotalLessonsCount,
			&i.LastLessonID,
			&i.LastAccessedAt,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.CourseSlug,
			&i.CourseThumbnail,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContinueLearningCourses = `-- name: GetContinueLearningCourses :many
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    c.title as course_title,
    c.slug as course_slug,
    c.thumbnail_url as course_thumbnail,
    c.lesson_count as course_total_lessons,
    c.module_count as course_module_count,
    u.name as author_name,
    u.avatar_url as author_avatar,
    l.id as last_lesson_id,
    l.title as last_lesson_title,
    m.title as last_module_title
FROM course_enrollments e
JOIN courses c ON e.course_id = c.id
JOIN users u ON c.author_id = u.id
LEFT JOIN lessons l ON e.last_lesson_id = l.id
LEFT JOIN modules m ON l.module_id = m.id
WHERE e.user_id = $1 AND e.tenant_id = $2 AND e.status = 'active' AND e.progress_percentage < 100
ORDER BY e.last_accessed_at DESC NULLS LAST, e.enrolled_at DESC
LIMIT $3
`

type GetContinueLearningCoursesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

type GetContinueLearningCoursesRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	CourseThumbnail       sql.NullString `json:"course_thumbnail"`
	CourseTotalLessons    int32          `json:"course_total_lessons"`
	CourseModuleCount     int32          `json:"course_module_count"`
	AuthorName            string         `json:"author_name"`
	AuthorAvatar          sql.NullString `json:"author_avatar"`
	LastLessonID_2        uuid.NullUUID  `json:"last_lesson_id_2"`
	LastLessonTitle       sql.NullString `json:"last_lesson_title"`
	LastModuleTitle       sql.NullString `json:"last_module_title"`
}

func (q *Queries) GetContinueLearningCourses(ctx context.Context, arg GetContinueLearningCoursesParams) ([]GetContinueLearningCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getContinueLearningCourses, arg.UserID, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContinueLearningCoursesRow
	for rows.Next() {
		var i GetContinueLearningCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CourseID,
			&i.Status,
			&i.ProgressPercentage,
			&i.CompletedLessonsCount,
			&i.TotalLessonsCount,
			&i.LastLessonID,
			&i.LastAccessedAt,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.CourseSlug,
			&i.CourseThumbnail,
			&i.CourseTotalLessons,
			&i.CourseModuleCount,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LastLessonID_2,
			&i.LastLessonTitle,
			&i.LastModuleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT id, tenant_id, user_id, course_id, status, progress_percentage, completed_lessons_count, total_lessons_count, last_lesson_id, last_accessed_at, enrolled_at, completed_at, created_at, updated_at FROM course_enrollments WHERE id = $1
`

func (q *Queries) GetEnrollmentByID(ctx context.Context, id uuid.UUID) (CourseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentByID, id)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CompletedLessonsCount,
		&i.TotalLessonsCount,
		&i.LastLessonID,
		&i.LastAccessedAt,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentByUserAndCourse = `-- name: GetEnrollmentByUserAndCourse :one
SELECT id, tenant_id, user_id, course_id, status, progress_percentage, completed_lessons_count, total_lessons_count, last_lesson_id, last_accessed_at, enrolled_at, completed_at, created_at, updated_at FROM course_enrollments
WHERE user_id = $1 AND course_id = $2
`

type GetEnrollmentByUserAndCourseParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) GetEnrollmentByUserAndCourse(ctx context.Context, arg GetEnrollmentByUserAndCourseParams) (CourseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentByUserAndCourse, arg.UserID, arg.CourseID)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CompletedLessonsCount,
		&i.TotalLessonsCount,
		&i.LastLessonID,
		&i.LastAccessedAt,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentWithProgress = `-- name: GetEnrollmentWithProgress :one
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    c.title as course_title,
    c.slug as course_slug,
    c.thumbnail_url as course_thumbnail,
    c.lesson_count as course_total_lessons,
    c.module_count as course_module_count,
    c.description as course_description,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM course_enrollments e
JOIN courses c ON e.course_id = c.id
JOIN users u ON c.author_id = u.id
WHERE e.id = $1
`

type GetEnrollmentWithProgressRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	CourseThumbnail       sql.NullString `json:"course_thumbnail"`
	CourseTotalLessons    int32          `json:"course_total_lessons"`
	CourseModuleCount     int32          `json:"course_module_count"`
	CourseDescription     sql.NullString `json:"course_description"`
	AuthorName            string         `json:"author_name"`
	AuthorAvatar          sql.NullString `json:"author_avatar"`
}

func (q *Queries) GetEnrollmentWithProgress(ctx context.Context, id uuid.UUID) (GetEnrollmentWithProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentWithProgress, id)
	var i GetEnrollmentWithProgressRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CompletedLessonsCount,
		&i.TotalLessonsCount,
		&i.LastLessonID,
		&i.LastAccessedAt,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseTitle,
		&i.CourseSlug,
		&i.CourseThumbnail,
		&i.CourseTotalLessons,
		&i.CourseModuleCount,
		&i.CourseDescription,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const getEnrollmentWithProgressByUserAndCourse = `-- name: GetEnrollmentWithProgressByUserAndCourse :one
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    c.title as course_title,
    c.slug as course_slug,
    c.thumbnail_url as course_thumbnail,
    c.lesson_count as course_total_lessons,
    c.module_count as course_module_count,
    c.description as course_description,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM course_enrollments e
JOIN courses c ON e.course_id = c.id
JOIN users u ON c.author_id = u.id
WHERE e.user_id = $1 AND e.course_id = $2
`

type GetEnrollmentWithProgressByUserAndCourseParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

type GetEnrollmentWithProgressByUserAndCourseRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	CourseThumbnail       sql.NullString `json:"course_thumbnail"`
	CourseTotalLessons    int32          `json:"course_total_lessons"`
	CourseModuleCount     int32          `json:"course_module_count"`
	CourseDescription     sql.NullString `json:"course_description"`
	AuthorName            string         `json:"author_name"`
	AuthorAvatar          sql.NullString `json:"author_avatar"`
}

func (q *Queries) GetEnrollmentWithProgressByUserAndCourse(ctx context.Context, arg GetEnrollmentWithProgressByUserAndCourseParams) (GetEnrollmentWithProgressByUserAndCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentWithProgressByUserAndCourse, arg.UserID, arg.CourseID)
	var i GetEnrollmentWithProgressByUserAndCourseRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CourseID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CompletedLessonsCount,
		&i.TotalLessonsCount,
		&i.LastLessonID,
		&i.LastAccessedAt,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseTitle,
		&i.CourseSlug,
		&i.CourseThumbnail,
		&i.CourseTotalLessons,
		&i.CourseModuleCount,
		&i.CourseDescription,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const isUserEnrolled = `-- name: IsUserEnrolled :one
SELECT EXISTS (
    SELECT 1 FROM course_enrollments
    WHERE user_id = $1 AND course_id = $2 AND status IN ('active', 'completed')
) as enrolled
`

type IsUserEnrolledParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) IsUserEnrolled(ctx context.Context, arg IsUserEnrolledParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserEnrolled, arg.UserID, arg.CourseID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const listEnrollmentsByCourse = `-- name: ListEnrollmentsByCourse :many
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar
FROM course_enrollments e
JOIN users u ON e.user_id = u.id
WHERE e.course_id = $1
ORDER BY e.enrolled_at DESC
LIMIT $2 OFFSET $3
`

type ListEnrollmentsByCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListEnrollmentsByCourseRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	UserName              string         `json:"user_name"`
	UserEmail             string         `json:"user_email"`
	UserAvatar            sql.NullString `json:"user_avatar"`
}

func (q *Queries) ListEnrollmentsByCourse(ctx context.Context, arg ListEnrollmentsByCourseParams) ([]ListEnrollmentsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsByCourse, arg.CourseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsByCourseRow
	for rows.Next() {
		var i ListEnrollmentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CourseID,
			&i.Status,
			&i.ProgressPercentage,
			&i.CompletedLessonsCount,
			&i.TotalLessonsCount,
			&i.LastLessonID,
			&i.LastAccessedAt,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByUser = `-- name: ListEnrollmentsByUser :many
SELECT
    e.id, e.tenant_id, e.user_id, e.course_id, e.status, e.progress_percentage, e.completed_lessons_count, e.total_lessons_count, e.last_lesson_id, e.last_accessed_at, e.enrolled_at, e.completed_at, e.created_at, e.updated_at,
    c.title as course_title,
    c.slug as course_slug,
    c.thumbnail_url as course_thumbnail,
    c.lesson_count as course_total_lessons,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM course_enrollments e
JOIN courses c ON e.course_id = c.id
JOIN users u ON c.author_id = u.id
WHERE e.user_id = $1 AND e.tenant_id = $2 AND e.status = 'active'
ORDER BY e.last_accessed_at DESC NULLS LAST, e.enrolled_at DESC
LIMIT $3 OFFSET $4
`

type ListEnrollmentsByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListEnrollmentsByUserRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CourseID              uuid.UUID      `json:"course_id"`
	Status                string         `json:"status"`
	ProgressPercentage    int32          `json:"progress_percentage"`
	CompletedLessonsCount int32          `json:"completed_lessons_count"`
	TotalLessonsCount     int32          `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID  `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime   `json:"last_accessed_at"`
	EnrolledAt            time.Time      `json:"enrolled_at"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	CourseThumbnail       sql.NullString `json:"course_thumbnail"`
	CourseTotalLessons    int32          `json:"course_total_lessons"`
	AuthorName            string         `json:"author_name"`
	AuthorAvatar          sql.NullString `json:"author_avatar"`
}

func (q *Queries) ListEnrollmentsByUser(ctx context.Context, arg ListEnrollmentsByUserParams) ([]ListEnrollmentsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsByUser,
		arg.UserID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsByUserRow
	for rows.Next() {
		var i ListEnrollmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CourseID,
			&i.Status,
			&i.ProgressPercentage,
			&i.CompletedLessonsCount,
			&i.TotalLessonsCount,
			&i.LastLessonID,
			&i.LastAccessedAt,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.CourseSlug,
			&i.CourseThumbnail,
			&i.CourseTotalLessons,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollmentLastAccessed = `-- name: UpdateEnrollmentLastAccessed :exec
UPDATE course_enrollments
SET last_accessed_at = NOW(), last_lesson_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateEnrollmentLastAccessedParams struct {
	ID           uuid.UUID     `json:"id"`
	LastLessonID uuid.NullUUID `json:"last_lesson_id"`
}

func (q *Queries) UpdateEnrollmentLastAccessed(ctx context.Context, arg UpdateEnrollmentLastAccessedParams) error {
	_, err := q.db.ExecContext(ctx, updateEnrollmentLastAccessed, arg.ID, arg.LastLessonID)
	return err
}
