// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lesson_progress.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countCompletedLessonsByEnrollment = `-- name: CountCompletedLessonsByEnrollment :one
SELECT COUNT(*) as count FROM lesson_progress
WHERE enrollment_id = $1 AND status = 'completed'
`

func (q *Queries) CountCompletedLessonsByEnrollment(ctx context.Context, enrollmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedLessonsByEnrollment, enrollmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLessonProgress = `-- name: CreateLessonProgress :one

INSERT INTO lesson_progress (tenant_id, enrollment_id, lesson_id, status, started_at)
VALUES ($1, $2, $3, 'in_progress', NOW())
RETURNING id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at
`

type CreateLessonProgressParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
}

// ============================================================================
// LESSON PROGRESS
// ============================================================================
func (q *Queries) CreateLessonProgress(ctx context.Context, arg CreateLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, createLessonProgress, arg.TenantID, arg.EnrollmentID, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLessonProgress = `-- name: DeleteLessonProgress :exec
DELETE FROM lesson_progress
WHERE enrollment_id = $1 AND lesson_id = $2
`

type DeleteLessonProgressParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
}

func (q *Queries) DeleteLessonProgress(ctx context.Context, arg DeleteLessonProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteLessonProgress, arg.EnrollmentID, arg.LessonID)
	return err
}

const getFirstLesson = `-- name: GetFirstLesson :one
SELECT
    l.id,
    l.title,
    l.position,
    m.id as module_id,
    m.title as module_title,
    m.position as module_position
FROM lessons l
JOIN modules m ON l.module_id = m.id
WHERE m.course_id = $1
ORDER BY m.position ASC, l.position ASC
LIMIT 1
`

type GetFirstLessonRow struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Position       int32     `json:"position"`
	ModuleID       uuid.UUID `json:"module_id"`
	ModuleTitle    string    `json:"module_title"`
	ModulePosition int32     `json:"module_position"`
}

func (q *Queries) GetFirstLesson(ctx context.Context, courseID uuid.UUID) (GetFirstLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getFirstLesson, courseID)
	var i GetFirstLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.ModuleID,
		&i.ModuleTitle,
		&i.ModulePosition,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at FROM lesson_progress
WHERE enrollment_id = $1 AND lesson_id = $2
`

type GetLessonProgressParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, getLessonProgress, arg.EnrollmentID, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonProgressByID = `-- name: GetLessonProgressByID :one
SELECT id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at FROM lesson_progress WHERE id = $1
`

func (q *Queries) GetLessonProgressByID(ctx context.Context, id uuid.UUID) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, getLessonProgressByID, id)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonWithProgressAndCourse = `-- name: GetLessonWithProgressAndCourse :one
SELECT
    l.id, l.tenant_id, l.module_id, l.title, l.description, l.content, l.content_format, l.video_id, l.position, l.duration_minutes, l.is_free_preview, l.created_at, l.updated_at,
    m.id as module_id,
    m.title as module_title,
    m.position as module_position,
    m.course_id as course_id,
    c.title as course_title,
    c.slug as course_slug,
    v.title as video_title,
    v.playback_url as video_playback_url,
    v.thumbnail_url as video_thumbnail_url,
    v.duration_seconds as video_duration,
    v.status as video_status,
    lp.id as progress_id,
    lp.status as progress_status,
    lp.watch_duration_seconds as progress_watch_duration,
    lp.completed_at as progress_completed_at
FROM lessons l
JOIN modules m ON l.module_id = m.id
JOIN courses c ON m.course_id = c.id
LEFT JOIN videos v ON l.video_id = v.id
LEFT JOIN lesson_progress lp ON l.id = lp.lesson_id AND lp.enrollment_id = $2
WHERE l.id = $1
`

type GetLessonWithProgressAndCourseParams struct {
	ID           uuid.UUID `json:"id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

type GetLessonWithProgressAndCourseRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenant_id"`
	ModuleID              uuid.UUID      `json:"module_id"`
	Title                 string         `json:"title"`
	Description           sql.NullString `json:"description"`
	Content               sql.NullString `json:"content"`
	ContentFormat         string         `json:"content_format"`
	VideoID               uuid.NullUUID  `json:"video_id"`
	Position              int32          `json:"position"`
	DurationMinutes       sql.NullInt32  `json:"duration_minutes"`
	IsFreePreview         bool           `json:"is_free_preview"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ModuleID_2            uuid.UUID      `json:"module_id_2"`
	ModuleTitle           string         `json:"module_title"`
	ModulePosition        int32          `json:"module_position"`
	CourseID              uuid.UUID      `json:"course_id"`
	CourseTitle           string         `json:"course_title"`
	CourseSlug            string         `json:"course_slug"`
	VideoTitle            sql.NullString `json:"video_title"`
	VideoPlaybackUrl      sql.NullString `json:"video_playback_url"`
	VideoThumbnailUrl     sql.NullString `json:"video_thumbnail_url"`
	VideoDuration         sql.NullInt32  `json:"video_duration"`
	VideoStatus           sql.NullString `json:"video_status"`
	ProgressID            uuid.NullUUID  `json:"progress_id"`
	ProgressStatus        sql.NullString `json:"progress_status"`
	ProgressWatchDuration sql.NullInt32  `json:"progress_watch_duration"`
	ProgressCompletedAt   sql.NullTime   `json:"progress_completed_at"`
}

func (q *Queries) GetLessonWithProgressAndCourse(ctx context.Context, arg GetLessonWithProgressAndCourseParams) (GetLessonWithProgressAndCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getLessonWithProgressAndCourse, arg.ID, arg.EnrollmentID)
	var i GetLessonWithProgressAndCourseRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.ContentFormat,
		&i.VideoID,
		&i.Position,
		&i.DurationMinutes,
		&i.IsFreePreview,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleID_2,
		&i.ModuleTitle,
		&i.ModulePosition,
		&i.CourseID,
		&i.CourseTitle,
		&i.CourseSlug,
		&i.VideoTitle,
		&i.VideoPlaybackUrl,
		&i.VideoThumbnailUrl,
		&i.VideoDuration,
		&i.VideoStatus,
		&i.ProgressID,
		&i.ProgressStatus,
		&i.ProgressWatchDuration,
		&i.ProgressCompletedAt,
	)
	return i, err
}

const getNextIncompleteLesson = `-- name: GetNextIncompleteLesson :one
SELECT
    l.id,
    l.title,
    l.position,
    m.id as module_id,
    m.title as module_title,
    m.position as module_position
FROM lessons l
JOIN modules m ON l.module_id = m.id
WHERE m.course_id = $1
AND l.id NOT IN (
    SELECT lesson_id FROM lesson_progress
    WHERE enrollment_id = $2 AND status = 'completed'
)
ORDER BY m.position ASC, l.position ASC
LIMIT 1
`

type GetNextIncompleteLessonParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

type GetNextIncompleteLessonRow struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Position       int32     `json:"position"`
	ModuleID       uuid.UUID `json:"module_id"`
	ModuleTitle    string    `json:"module_title"`
	ModulePosition int32     `json:"module_position"`
}

func (q *Queries) GetNextIncompleteLesson(ctx context.Context, arg GetNextIncompleteLessonParams) (GetNextIncompleteLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getNextIncompleteLesson, arg.CourseID, arg.EnrollmentID)
	var i GetNextIncompleteLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Position,
		&i.ModuleID,
		&i.ModuleTitle,
		&i.ModulePosition,
	)
	return i, err
}

const getNextLesson = `-- name: GetNextLesson :one
SELECT
    l.id,
    l.title,
    m.position as module_position,
    l.position as lesson_position
FROM lessons l
JOIN modules m ON l.module_id = m.id
WHERE m.course_id = $1
AND (m.position > $2 OR (m.position = $2 AND l.position > $3))
ORDER BY m.position ASC, l.position ASC
LIMIT 1
`

type GetNextLessonParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	Position   int32     `json:"position"`
	Position_2 int32     `json:"position_2"`
}

type GetNextLessonRow struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	ModulePosition int32     `json:"module_position"`
	LessonPosition int32     `json:"lesson_position"`
}

func (q *Queries) GetNextLesson(ctx context.Context, arg GetNextLessonParams) (GetNextLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getNextLesson, arg.CourseID, arg.Position, arg.Position_2)
	var i GetNextLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ModulePosition,
		&i.LessonPosition,
	)
	return i, err
}

const getPreviousLesson = `-- name: GetPreviousLesson :one
SELECT
    l.id,
    l.title,
    m.position as module_position,
    l.position as lesson_position
FROM lessons l
JOIN modules m ON l.module_id = m.id
WHERE m.course_id = $1
AND (m.position < $2 OR (m.position = $2 AND l.position < $3))
ORDER BY m.position DESC, l.position DESC
LIMIT 1
`

type GetPreviousLessonParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	Position   int32     `json:"position"`
	Position_2 int32     `json:"position_2"`
}

type GetPreviousLessonRow struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	ModulePosition int32     `json:"module_position"`
	LessonPosition int32     `json:"lesson_position"`
}

func (q *Queries) GetPreviousLesson(ctx context.Context, arg GetPreviousLessonParams) (GetPreviousLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getPreviousLesson, arg.CourseID, arg.Position, arg.Position_2)
	var i GetPreviousLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ModulePosition,
		&i.LessonPosition,
	)
	return i, err
}

const listLessonProgressByEnrollment = `-- name: ListLessonProgressByEnrollment :many
SELECT id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at FROM lesson_progress
WHERE enrollment_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListLessonProgressByEnrollment(ctx context.Context, enrollmentID uuid.UUID) ([]LessonProgress, error) {
	rows, err := q.db.QueryContext(ctx, listLessonProgressByEnrollment, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonProgress
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EnrollmentID,
			&i.LessonID,
			&i.Status,
			&i.WatchDurationSeconds,
			&i.VideoTotalSeconds,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsWithProgress = `-- name: ListLessonsWithProgress :many
SELECT
    l.id,
    l.title,
    l.position,
    l.duration_minutes,
    l.is_free_preview,
    l.video_id,
    m.id as module_id,
    m.title as module_title,
    m.position as module_position,
    v.duration_seconds as video_duration,
    v.thumbnail_url as video_thumbnail,
    COALESCE(lp.status, 'not_started') as progress_status,
    lp.completed_at as progress_completed_at
FROM lessons l
JOIN modules m ON l.module_id = m.id
LEFT JOIN videos v ON l.video_id = v.id
LEFT JOIN lesson_progress lp ON l.id = lp.lesson_id AND lp.enrollment_id = $2
WHERE m.course_id = $1
ORDER BY m.position ASC, l.position ASC
`

type ListLessonsWithProgressParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

type ListLessonsWithProgressRow struct {
	ID                  uuid.UUID      `json:"id"`
	Title               string         `json:"title"`
	Position            int32          `json:"position"`
	DurationMinutes     sql.NullInt32  `json:"duration_minutes"`
	IsFreePreview       bool           `json:"is_free_preview"`
	VideoID             uuid.NullUUID  `json:"video_id"`
	ModuleID            uuid.UUID      `json:"module_id"`
	ModuleTitle         string         `json:"module_title"`
	ModulePosition      int32          `json:"module_position"`
	VideoDuration       sql.NullInt32  `json:"video_duration"`
	VideoThumbnail      sql.NullString `json:"video_thumbnail"`
	ProgressStatus      string         `json:"progress_status"`
	ProgressCompletedAt sql.NullTime   `json:"progress_completed_at"`
}

func (q *Queries) ListLessonsWithProgress(ctx context.Context, arg ListLessonsWithProgressParams) ([]ListLessonsWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsWithProgress, arg.CourseID, arg.EnrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonsWithProgressRow
	for rows.Next() {
		var i ListLessonsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Position,
			&i.DurationMinutes,
			&i.IsFreePreview,
			&i.VideoID,
			&i.ModuleID,
			&i.ModuleTitle,
			&i.ModulePosition,
			&i.VideoDuration,
			&i.VideoThumbnail,
			&i.ProgressStatus,
			&i.ProgressCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLessonComplete = `-- name: MarkLessonComplete :one
INSERT INTO lesson_progress (tenant_id, enrollment_id, lesson_id, status, started_at, completed_at)
VALUES ($1, $2, $3, 'completed', COALESCE($4, NOW()), NOW())
ON CONFLICT (enrollment_id, lesson_id) DO UPDATE
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
RETURNING id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at
`

type MarkLessonCompleteParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	EnrollmentID uuid.UUID   `json:"enrollment_id"`
	LessonID     uuid.UUID   `json:"lesson_id"`
	Column4      interface{} `json:"column_4"`
}

func (q *Queries) MarkLessonComplete(ctx context.Context, arg MarkLessonCompleteParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, markLessonComplete,
		arg.TenantID,
		arg.EnrollmentID,
		arg.LessonID,
		arg.Column4,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markLessonIncomplete = `-- name: MarkLessonIncomplete :one
UPDATE lesson_progress
SET status = 'in_progress', completed_at = NULL, updated_at = NOW()
WHERE enrollment_id = $1 AND lesson_id = $2
RETURNING id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at
`

type MarkLessonIncompleteParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
}

func (q *Queries) MarkLessonIncomplete(ctx context.Context, arg MarkLessonIncompleteParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, markLessonIncomplete, arg.EnrollmentID, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoProgress = `-- name: UpdateVideoProgress :one
INSERT INTO lesson_progress (tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at)
VALUES ($1, $2, $3, 'in_progress', $4, $5, NOW())
ON CONFLICT (enrollment_id, lesson_id) DO UPDATE
SET watch_duration_seconds = $4, video_total_seconds = COALESCE($5, lesson_progress.video_total_seconds), updated_at = NOW()
RETURNING id, tenant_id, enrollment_id, lesson_id, status, watch_duration_seconds, video_total_seconds, started_at, completed_at, created_at, updated_at
`

type UpdateVideoProgressParams struct {
	TenantID             uuid.UUID     `json:"tenant_id"`
	EnrollmentID         uuid.UUID     `json:"enrollment_id"`
	LessonID             uuid.UUID     `json:"lesson_id"`
	WatchDurationSeconds int32         `json:"watch_duration_seconds"`
	VideoTotalSeconds    sql.NullInt32 `json:"video_total_seconds"`
}

func (q *Queries) UpdateVideoProgress(ctx context.Context, arg UpdateVideoProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, updateVideoProgress,
		arg.TenantID,
		arg.EnrollmentID,
		arg.LessonID,
		arg.WatchDurationSeconds,
		arg.VideoTotalSeconds,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.Status,
		&i.WatchDurationSeconds,
		&i.VideoTotalSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
