// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const checkUserLikedComments = `-- name: CheckUserLikedComments :many
SELECT comment_id FROM likes
WHERE user_id = $1 AND comment_id = ANY($2::uuid[])
`

type CheckUserLikedCommentsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) CheckUserLikedComments(ctx context.Context, arg CheckUserLikedCommentsParams) ([]uuid.NullUUID, error) {
	rows, err := q.db.QueryContext(ctx, checkUserLikedComments, arg.UserID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.NullUUID
	for rows.Next() {
		var comment_id uuid.NullUUID
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkUserLikedPosts = `-- name: CheckUserLikedPosts :many
SELECT post_id FROM likes
WHERE user_id = $1 AND post_id = ANY($2::uuid[])
`

type CheckUserLikedPostsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) CheckUserLikedPosts(ctx context.Context, arg CheckUserLikedPostsParams) ([]uuid.NullUUID, error) {
	rows, err := q.db.QueryContext(ctx, checkUserLikedPosts, arg.UserID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.NullUUID
	for rows.Next() {
		var post_id uuid.NullUUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCommentLike = `-- name: CreateCommentLike :one
INSERT INTO likes (tenant_id, user_id, comment_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, post_id, comment_id, created_at
`

type CreateCommentLikeParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
}

func (q *Queries) CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createCommentLike, arg.TenantID, arg.UserID, arg.CommentID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const createPostLike = `-- name: CreatePostLike :one
INSERT INTO likes (tenant_id, user_id, post_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, post_id, comment_id, created_at
`

type CreatePostLikeParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	UserID   uuid.UUID     `json:"user_id"`
	PostID   uuid.NullUUID `json:"post_id"`
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createPostLike, arg.TenantID, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommentLike = `-- name: DeleteCommentLike :exec
DELETE FROM likes
WHERE tenant_id = $1 AND user_id = $2 AND comment_id = $3
`

type DeleteCommentLikeParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
}

func (q *Queries) DeleteCommentLike(ctx context.Context, arg DeleteCommentLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentLike, arg.TenantID, arg.UserID, arg.CommentID)
	return err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM likes
WHERE tenant_id = $1 AND user_id = $2 AND post_id = $3
`

type DeletePostLikeParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	UserID   uuid.UUID     `json:"user_id"`
	PostID   uuid.NullUUID `json:"post_id"`
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.ExecContext(ctx, deletePostLike, arg.TenantID, arg.UserID, arg.PostID)
	return err
}

const getCommentLike = `-- name: GetCommentLike :one
SELECT id, tenant_id, user_id, post_id, comment_id, created_at FROM likes
WHERE user_id = $1 AND comment_id = $2
`

type GetCommentLikeParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
}

func (q *Queries) GetCommentLike(ctx context.Context, arg GetCommentLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, getCommentLike, arg.UserID, arg.CommentID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentLikesCount = `-- name: GetCommentLikesCount :one
SELECT COUNT(*) as count FROM likes
WHERE comment_id = $1
`

func (q *Queries) GetCommentLikesCount(ctx context.Context, commentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommentLikesCount, commentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostLike = `-- name: GetPostLike :one
SELECT id, tenant_id, user_id, post_id, comment_id, created_at FROM likes
WHERE user_id = $1 AND post_id = $2
`

type GetPostLikeParams struct {
	UserID uuid.UUID     `json:"user_id"`
	PostID uuid.NullUUID `json:"post_id"`
}

func (q *Queries) GetPostLike(ctx context.Context, arg GetPostLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, getPostLike, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.CreatedAt,
	)
	return i, err
}

const getPostLikesCount = `-- name: GetPostLikesCount :one
SELECT COUNT(*) as count FROM likes
WHERE post_id = $1
`

func (q *Queries) GetPostLikesCount(ctx context.Context, postID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostLikesCount, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCommentLikes = `-- name: GetUserCommentLikes :many
SELECT comment_id FROM likes
WHERE user_id = $1 AND tenant_id = $2 AND comment_id IS NOT NULL
`

type GetUserCommentLikesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserCommentLikes(ctx context.Context, arg GetUserCommentLikesParams) ([]uuid.NullUUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserCommentLikes, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.NullUUID
	for rows.Next() {
		var comment_id uuid.NullUUID
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPostLikes = `-- name: GetUserPostLikes :many
SELECT post_id FROM likes
WHERE user_id = $1 AND tenant_id = $2 AND post_id IS NOT NULL
`

type GetUserPostLikesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserPostLikes(ctx context.Context, arg GetUserPostLikesParams) ([]uuid.NullUUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserPostLikes, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.NullUUID
	for rows.Next() {
		var post_id uuid.NullUUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
