// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	Position    int32          `json:"position"`
	IsVisible   bool           `json:"is_visible"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Comment struct {
	ID         uuid.UUID     `json:"id"`
	TenantID   uuid.UUID     `json:"tenant_id"`
	PostID     uuid.UUID     `json:"post_id"`
	AuthorID   uuid.UUID     `json:"author_id"`
	ParentID   uuid.NullUUID `json:"parent_id"`
	Content    string        `json:"content"`
	LikeCount  int32         `json:"like_count"`
	ReplyCount int32         `json:"reply_count"`
	Status     string        `json:"status"`
	Depth      int32         `json:"depth"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type Course struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Status       string         `json:"status"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	ModuleCount  int32          `json:"module_count"`
	LessonCount  int32          `json:"lesson_count"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type CourseEnrollment struct {
	ID                    uuid.UUID     `json:"id"`
	TenantID              uuid.UUID     `json:"tenant_id"`
	UserID                uuid.UUID     `json:"user_id"`
	CourseID              uuid.UUID     `json:"course_id"`
	Status                string        `json:"status"`
	ProgressPercentage    int32         `json:"progress_percentage"`
	CompletedLessonsCount int32         `json:"completed_lessons_count"`
	TotalLessonsCount     int32         `json:"total_lessons_count"`
	LastLessonID          uuid.NullUUID `json:"last_lesson_id"`
	LastAccessedAt        sql.NullTime  `json:"last_accessed_at"`
	EnrolledAt            time.Time     `json:"enrolled_at"`
	CompletedAt           sql.NullTime  `json:"completed_at"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

type Lesson struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	ModuleID        uuid.UUID      `json:"module_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Content         sql.NullString `json:"content"`
	ContentFormat   string         `json:"content_format"`
	VideoID         uuid.NullUUID  `json:"video_id"`
	Position        int32          `json:"position"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	IsFreePreview   bool           `json:"is_free_preview"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type LessonProgress struct {
	ID                   uuid.UUID     `json:"id"`
	TenantID             uuid.UUID     `json:"tenant_id"`
	EnrollmentID         uuid.UUID     `json:"enrollment_id"`
	LessonID             uuid.UUID     `json:"lesson_id"`
	Status               string        `json:"status"`
	WatchDurationSeconds int32         `json:"watch_duration_seconds"`
	VideoTotalSeconds    sql.NullInt32 `json:"video_total_seconds"`
	StartedAt            sql.NullTime  `json:"started_at"`
	CompletedAt          sql.NullTime  `json:"completed_at"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

type Like struct {
	ID        uuid.UUID     `json:"id"`
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	PostID    uuid.NullUUID `json:"post_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Module struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	CourseID    uuid.UUID      `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    int32          `json:"position"`
	LessonCount int32          `json:"lesson_count"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Notification struct {
	ID        uuid.UUID             `json:"id"`
	TenantID  uuid.UUID             `json:"tenant_id"`
	UserID    uuid.UUID             `json:"user_id"`
	Type      string                `json:"type"`
	Title     string                `json:"title"`
	Message   sql.NullString        `json:"message"`
	Data      pqtype.NullRawMessage `json:"data"`
	ReadAt    sql.NullTime          `json:"read_at"`
	CreatedAt time.Time             `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Post struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	CategoryID    uuid.NullUUID  `json:"category_id"`
	AuthorID      uuid.UUID      `json:"author_id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Content       sql.NullString `json:"content"`
	ContentFormat string         `json:"content_format"`
	Excerpt       sql.NullString `json:"excerpt"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Status        string         `json:"status"`
	PublishedAt   sql.NullTime   `json:"published_at"`
	ViewCount     int32          `json:"view_count"`
	LikeCount     int32          `json:"like_count"`
	CommentCount  int32          `json:"comment_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Priority    int32          `json:"priority"`
	IsDefault   bool           `json:"is_default"`
	IsSystem    bool           `json:"is_system"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Tenant struct {
	ID                   uuid.UUID             `json:"id"`
	Slug                 string                `json:"slug"`
	Name                 string                `json:"name"`
	Description          sql.NullString        `json:"description"`
	LogoUrl              sql.NullString        `json:"logo_url"`
	Settings             pqtype.NullRawMessage `json:"settings"`
	Status               string                `json:"status"`
	BillingStatus        string                `json:"billing_status"`
	StripeCustomerID     sql.NullString        `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString        `json:"stripe_subscription_id"`
	PlanID               sql.NullString        `json:"plan_id"`
	CreatedAt            time.Time             `json:"created_at"`
	UpdatedAt            time.Time             `json:"updated_at"`
}

type TenantMember struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	UserID      uuid.UUID      `json:"user_id"`
	RoleID      uuid.UUID      `json:"role_id"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	Status      string         `json:"status"`
	JoinedAt    time.Time      `json:"joined_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	Name            string         `json:"name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	EmailVerifiedAt sql.NullTime   `json:"email_verified_at"`
	Status          string         `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Video struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	UploaderID      uuid.UUID      `json:"uploader_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	ExternalID      sql.NullString `json:"external_id"`
	Provider        string         `json:"provider"`
	OriginalUrl     sql.NullString `json:"original_url"`
	PlaybackUrl     sql.NullString `json:"playback_url"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	FileSizeBytes   sql.NullInt64  `json:"file_size_bytes"`
	Resolution      sql.NullString `json:"resolution"`
	Status          string         `json:"status"`
	ErrorMessage    sql.NullString `json:"error_message"`
	PostID          uuid.NullUUID  `json:"post_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type WebhookEvent struct {
	ID             uuid.UUID       `json:"id"`
	Provider       string          `json:"provider"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	Status         string          `json:"status"`
	ProcessedAt    sql.NullTime    `json:"processed_at"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
	CreatedAt      time.Time       `json:"created_at"`
}
