// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countModulesByCourse = `-- name: CountModulesByCourse :one
SELECT COUNT(*) as count FROM modules WHERE course_id = $1
`

func (q *Queries) CountModulesByCourse(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModulesByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModule = `-- name: CreateModule :one

INSERT INTO modules (tenant_id, course_id, title, description, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, course_id, title, description, position, lesson_count, created_at, updated_at
`

type CreateModuleParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	CourseID    uuid.UUID      `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Position    int32          `json:"position"`
}

// ============================================================================
// MODULES
// ============================================================================
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, createModule,
		arg.TenantID,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteModule, id)
	return err
}

const getMaxModulePosition = `-- name: GetMaxModulePosition :one
SELECT COALESCE(MAX(position), -1)::int as max_position FROM modules WHERE course_id = $1
`

func (q *Queries) GetMaxModulePosition(ctx context.Context, courseID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxModulePosition, courseID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getModuleByID = `-- name: GetModuleByID :one
SELECT id, tenant_id, course_id, title, description, position, lesson_count, created_at, updated_at FROM modules WHERE id = $1
`

func (q *Queries) GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModuleByID, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModulesByCourse = `-- name: ListModulesByCourse :many
SELECT id, tenant_id, course_id, title, description, position, lesson_count, created_at, updated_at FROM modules
WHERE course_id = $1
ORDER BY position ASC
`

func (q *Queries) ListModulesByCourse(ctx context.Context, courseID uuid.UUID) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModulesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.LessonCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderModulesAfterDelete = `-- name: ReorderModulesAfterDelete :exec
UPDATE modules
SET position = position - 1, updated_at = NOW()
WHERE course_id = $1 AND position > $2
`

type ReorderModulesAfterDeleteParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Position int32     `json:"position"`
}

func (q *Queries) ReorderModulesAfterDelete(ctx context.Context, arg ReorderModulesAfterDeleteParams) error {
	_, err := q.db.ExecContext(ctx, reorderModulesAfterDelete, arg.CourseID, arg.Position)
	return err
}

const shiftModulePositionsDown = `-- name: ShiftModulePositionsDown :exec
UPDATE modules
SET position = position - 1, updated_at = NOW()
WHERE course_id = $1 AND position > $2 AND position <= $3
`

type ShiftModulePositionsDownParams struct {
	CourseID   uuid.UUID `json:"course_id"`
	Position   int32     `json:"position"`
	Position_2 int32     `json:"position_2"`
}

func (q *Queries) ShiftModulePositionsDown(ctx context.Context, arg ShiftModulePositionsDownParams) error {
	_, err := q.db.ExecContext(ctx, shiftModulePositionsDown, arg.CourseID, arg.Position, arg.Position_2)
	return err
}

const shiftModulePositionsUp = `-- name: ShiftModulePositionsUp :exec
UPDATE modules
SET position = position + 1, updated_at = NOW()
WHERE course_id = $1 AND position >= $2
`

type ShiftModulePositionsUpParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Position int32     `json:"position"`
}

func (q *Queries) ShiftModulePositionsUp(ctx context.Context, arg ShiftModulePositionsUpParams) error {
	_, err := q.db.ExecContext(ctx, shiftModulePositionsUp, arg.CourseID, arg.Position)
	return err
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET title = $2, description = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, course_id, title, description, position, lesson_count, created_at, updated_at
`

type UpdateModuleParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, updateModule, arg.ID, arg.Title, arg.Description)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.LessonCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModulePosition = `-- name: UpdateModulePosition :exec
UPDATE modules SET position = $2, updated_at = NOW() WHERE id = $1
`

type UpdateModulePositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateModulePosition(ctx context.Context, arg UpdateModulePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateModulePosition, arg.ID, arg.Position)
	return err
}
