// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, slug, name, description, priority, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Priority    int32          `json:"priority"`
	IsDefault   bool           `json:"is_default"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.IsDefault,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.IsDefault,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getDefaultRole = `-- name: GetDefaultRole :one
SELECT id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 AND is_default = true LIMIT 1
`

func (q *Queries) GetDefaultRole(ctx context.Context, tenantID uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getDefaultRole, tenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.IsDefault,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberPermissions = `-- name: GetMemberPermissions :many
SELECT p.code FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
JOIN tenant_members tm ON rp.role_id = tm.role_id
WHERE tm.tenant_id = $1 AND tm.user_id = $2 AND tm.status = 'active'
`

type GetMemberPermissionsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberPermissions(ctx context.Context, arg GetMemberPermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMemberPermissions, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.IsDefault,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 AND slug = $2
`

type GetRoleBySlugParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) GetRoleBySlug(ctx context.Context, arg GetRoleBySlugParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleBySlug, arg.TenantID, arg.Slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.IsDefault,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.code, p.name, p.description, p.category, p.created_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM permissions p
    JOIN role_permissions rp ON p.id = rp.permission_id
    JOIN tenant_members tm ON rp.role_id = tm.role_id
    WHERE tm.tenant_id = $1
    AND tm.user_id = $2
    AND tm.status = 'active'
    AND p.code = $3
) as has_permission
`

type HasPermissionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Code     string    `json:"code"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPermission, arg.TenantID, arg.UserID, arg.Code)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, name, description, category, created_at FROM permissions ORDER BY category, code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 ORDER BY priority DESC
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.IsDefault,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RemoveRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, removeRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, priority = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, slug, name, description, priority, is_default, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Priority    int32          `json:"priority"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Priority,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.IsDefault,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
