// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (tenant_id, post_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, post_id, author_id, parent_id, content, like_count, reply_count, status, depth, created_at, updated_at
`

type CreateCommentParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	PostID   uuid.UUID     `json:"post_id"`
	AuthorID uuid.UUID     `json:"author_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.TenantID,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.ReplyCount,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementCommentLikes = `-- name: DecrementCommentLikes :exec
UPDATE comments SET like_count = like_count - 1 WHERE id = $1 AND like_count > 0
`

func (q *Queries) DecrementCommentLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCommentLikes, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments SET status = 'deleted', updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, tenant_id, post_id, author_id, parent_id, content, like_count, reply_count, status, depth, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.ReplyCount,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideComment = `-- name: HideComment :exec
UPDATE comments SET status = 'hidden', updated_at = NOW() WHERE id = $1
`

func (q *Queries) HideComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, hideComment, id)
	return err
}

const incrementCommentLikes = `-- name: IncrementCommentLikes :exec
UPDATE comments SET like_count = like_count + 1 WHERE id = $1
`

func (q *Queries) IncrementCommentLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCommentLikes, id)
	return err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT
    c.id, c.tenant_id, c.post_id, c.author_id, c.parent_id, c.content, c.like_count, c.reply_count, c.status, c.depth, c.created_at, c.updated_at,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.post_id = $1 AND c.parent_id IS NULL AND c.status = 'visible'
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListCommentsByPostRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	PostID       uuid.UUID      `json:"post_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	ParentID     uuid.NullUUID  `json:"parent_id"`
	Content      string         `json:"content"`
	LikeCount    int32          `json:"like_count"`
	ReplyCount   int32          `json:"reply_count"`
	Status       string         `json:"status"`
	Depth        int32          `json:"depth"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AuthorName   string         `json:"author_name"`
	AuthorAvatar sql.NullString `json:"author_avatar"`
}

func (q *Queries) ListCommentsByPost(ctx context.Context, arg ListCommentsByPostParams) ([]ListCommentsByPostRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByPostRow
	for rows.Next() {
		var i ListCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT
    c.id, c.tenant_id, c.post_id, c.author_id, c.parent_id, c.content, c.like_count, c.reply_count, c.status, c.depth, c.created_at, c.updated_at,
    u.name as author_name,
    u.avatar_url as author_avatar
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.parent_id = $1 AND c.status = 'visible'
ORDER BY c.created_at ASC
`

type ListRepliesRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	PostID       uuid.UUID      `json:"post_id"`
	AuthorID     uuid.UUID      `json:"author_id"`
	ParentID     uuid.NullUUID  `json:"parent_id"`
	Content      string         `json:"content"`
	LikeCount    int32          `json:"like_count"`
	ReplyCount   int32          `json:"reply_count"`
	Status       string         `json:"status"`
	Depth        int32          `json:"depth"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	AuthorName   string         `json:"author_name"`
	AuthorAvatar sql.NullString `json:"author_avatar"`
}

func (q *Queries) ListReplies(ctx context.Context, parentID uuid.NullUUID) ([]ListRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, post_id, author_id, parent_id, content, like_count, reply_count, status, depth, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.LikeCount,
		&i.ReplyCount,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
