// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package database

import (
	"context"
	"database/sql"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, slug, name, description)
VALUES (uuid_generate_v4(), $1, $2, $3)
RETURNING id, slug, name, description, logo_url, settings, status, billing_status, stripe_customer_id, stripe_subscription_id, plan_id, created_at, updated_at
`

type CreateTenantParams struct {
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, arg.Slug, arg.Name, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.Settings,
		&i.Status,
		&i.BillingStatus,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, description, logo_url, settings, status, billing_status, stripe_customer_id, stripe_subscription_id, plan_id, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.Settings,
		&i.Status,
		&i.BillingStatus,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
