// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (provider, event_type, payload, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, provider, event_type, payload, status, processed_at, error_message, idempotency_key, created_at
`

type CreateWebhookEventParams struct {
	Provider       string          `json:"provider"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	IdempotencyKey sql.NullString  `json:"idempotency_key"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, createWebhookEvent,
		arg.Provider,
		arg.EventType,
		arg.Payload,
		arg.IdempotencyKey,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByKey = `-- name: GetWebhookEventByKey :one
SELECT id, provider, event_type, payload, status, processed_at, error_message, idempotency_key, created_at FROM webhook_events WHERE provider = $1 AND idempotency_key = $2
`

type GetWebhookEventByKeyParams struct {
	Provider       string         `json:"provider"`
	IdempotencyKey sql.NullString `json:"idempotency_key"`
}

func (q *Queries) GetWebhookEventByKey(ctx context.Context, arg GetWebhookEventByKeyParams) (WebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEventByKey, arg.Provider, arg.IdempotencyKey)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingWebhooks = `-- name: ListPendingWebhooks :many
SELECT id, provider, event_type, payload, status, processed_at, error_message, idempotency_key, created_at FROM webhook_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingWebhooks(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWebhooks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.ProcessedAt,
			&i.ErrorMessage,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_events
SET status = 'failed', error_message = $2, processed_at = NOW()
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID           uuid.UUID      `json:"id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.ExecContext(ctx, markWebhookFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE webhook_events
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markWebhookProcessed, id)
	return err
}
